import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

/**
 * Extract the icons we use out of Iconify's data, at authoring time (SKG-529).
 *
 * **Iconify as a source, never as a runtime.** `iconify-icon` and `@iconify/iconify` fetch their
 * paths from Iconify's API on first render — a network call to a third party, made from a client's
 * site, by a widget whose whole argument is that it needs nobody else's service. This reads the
 * `@iconify-json/ph` package, which is plain JSON and a devDependency, and writes the two paths we
 * use into `src/icon-data.ts`. Nothing about Iconify survives into `dist` except the geometry.
 *
 * The output is committed, so the widget builds with no generation step. What keeps it honest is
 * `icons.test.ts`, which compares every committed path against the installed package and fails on
 * a hand-edit or a stale copy.
 *
 * Run it with `pnpm icons:build` after adding a name to `WANTED`.
 */

/**
 * Phosphor, and the reason is its filled weight.
 *
 * Measured at the size this widget actually renders — 14px on the settings chip. Every stroked gear
 * tried there (`lucide:settings`, `tabler:settings`, `ph:gear`) collapses into a ring with bumps;
 * the filled ones stay legible. And a filled weight is only worth choosing a set for if the *next*
 * icon will have one too: Phosphor ships `-fill` for 1525 of its 1527 base icons, Tabler for 1056
 * of 5144, and Lucide has no systematic filled weight at all. Counted, not assumed.
 */
const SET = 'ph';

/** Our name for it, then Iconify's. Ours is what `icons.ts` and every call site say. */
const WANTED: Record<string, string> = {
  gear: 'gear-fill',
  close: 'x-bold',
};

type IconifyInfo = {
  name: string;
  version: string;
  author: { name: string; url: string };
  license: { title: string; spdx: string; url: string };
};

type IconifySet = {
  width?: number;
  height?: number;
  icons: Record<string, { body: string; width?: number; height?: number }>;
};

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

const set = require(`@iconify-json/${SET}/icons.json`) as IconifySet;
const info = require(`@iconify-json/${SET}/info.json`) as IconifyInfo;
const installed = (require(`@iconify-json/${SET}/package.json`) as { version: string }).version;

/**
 * Attributes, not markup.
 *
 * `icons.ts` builds every element with `createElementNS`, because an SVG string assigned through
 * `innerHTML` is parsed into the HTML namespace and renders nothing at all. So the body is taken
 * apart here rather than carried across as a string somebody would eventually be tempted to inject.
 *
 * Anything but a plain self-closing `<path>` is refused rather than dropped: an icon that needs a
 * `<circle>` or a `<g>` would otherwise ship as a subset of itself, drawn wrong and silently.
 */
function pathsOf(name: string, body: string): Record<string, string>[] {
  const paths: Record<string, string>[] = [];
  const remainder = body.replace(/<path\b([^>]*?)\/>/g, (_match, attributes: string) => {
    const attrs: Record<string, string> = {};
    for (const [, key, value] of attributes.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
      attrs[key as string] = value as string;
    }
    paths.push(attrs);

    return '';
  });

  if (remainder.trim().length > 0) {
    throw new Error(`${SET}:${name} is not made of paths alone — left over: ${remainder.trim().slice(0, 80)}`);
  }
  if (paths.length === 0) throw new Error(`${SET}:${name} has no path at all`);

  return paths;
}

const entries = Object.entries(WANTED).map(([ours, theirs]) => {
  const icon = set.icons[theirs];
  if (icon === undefined) throw new Error(`${SET}:${theirs} is not in the installed set`);

  const width = icon.width ?? set.width ?? 16;
  const height = icon.height ?? set.height ?? 16;

  return { ours, theirs, viewBox: `0 0 ${width} ${height}`, paths: pathsOf(theirs, icon.body) };
});

const source = `// Generated by \`pnpm icons:build\` from @iconify-json/${SET}@${installed}. Do not edit by hand:
// \`icons.test.ts\` compares every path below against the installed package and fails on a hand-edit.
//
// ${info.name} v${info.version} — ${info.license.title}, ${info.license.url}
// ${info.author.name}, ${info.author.url}
//
// The notice travels in packages/widget/THIRD-PARTY-NOTICES.md, because this geometry is compiled
// into dist rather than installed by the consumer. Same obligation as react-grab and zod (SKG-515).

/** Where each path came from, asserted by the test rather than trusted. */
export const ICON_SOURCE = {
  set: '${SET}',
  name: ${JSON.stringify(info.name)},
  version: ${JSON.stringify(installed)},
  license: ${JSON.stringify(info.license.spdx)},
  names: ${JSON.stringify(WANTED)},
} as const;

export type IconShape = { viewBox: string; paths: Record<string, string>[] };

// \`satisfies\` rather than an annotation, so each name is a property the compiler knows about:
// renaming one in \`WANTED\` without regenerating breaks \`icons.ts\` at build time instead of at
// mount time, in a widget that would otherwise throw inside somebody else's page.
export const ICON_DATA = {
${entries.map((e) => `  ${e.ours}: {\n    viewBox: '${e.viewBox}',\n    paths: ${JSON.stringify(e.paths)},\n  },`).join('\n')}
} satisfies Record<string, IconShape>;
`;

writeFileSync(join(here, 'src', 'icon-data.ts'), source);
console.log(`icons: wrote src/icon-data.ts — ${entries.map((e) => `${e.ours} (${SET}:${e.theirs})`).join(', ')}`);
