// Generated by `pnpm icons:build` from @iconify-json/ph@1.2.2. Do not edit by hand:
// `icons.test.ts` compares every path below against the installed package and fails on a hand-edit.
//
// Phosphor v2.1.1 — MIT, https://github.com/phosphor-icons/core/blob/main/LICENSE
// Phosphor Icons, https://github.com/phosphor-icons/core
//
// The notice travels in packages/widget/THIRD-PARTY-NOTICES.md, because this geometry is compiled
// into dist rather than installed by the consumer. Same obligation as react-grab and zod (SKG-515).

/** Where each path came from, asserted by the test rather than trusted. */
export const ICON_SOURCE = {
  set: 'ph',
  name: 'Phosphor',
  version: '1.2.2',
  license: 'MIT',
  names: { gear: 'gear-fill', close: 'x-bold' },
} as const;

export type IconShape = { viewBox: string; paths: Record<string, string>[] };

// `satisfies` rather than an annotation, so each name is a property the compiler knows about:
// renaming one in `WANTED` without regenerating breaks `icons.ts` at build time instead of at
// mount time, in a widget that would otherwise throw inside somebody else's page.
export const ICON_DATA = {
  gear: {
    viewBox: '0 0 256 256',
    paths: [
      {
        fill: 'currentColor',
        d: 'M216 130.16q.06-2.16 0-4.32l14.92-18.64a8 8 0 0 0 1.48-7.06a107.6 107.6 0 0 0-10.88-26.25a8 8 0 0 0-6-3.93l-23.72-2.64q-1.48-1.56-3-3L186 40.54a8 8 0 0 0-3.94-6a107.3 107.3 0 0 0-26.25-10.86a8 8 0 0 0-7.06 1.48L130.16 40h-4.32L107.2 25.11a8 8 0 0 0-7.06-1.48a107.6 107.6 0 0 0-26.25 10.88a8 8 0 0 0-3.93 6l-2.64 23.76q-1.56 1.49-3 3L40.54 70a8 8 0 0 0-6 3.94a107.7 107.7 0 0 0-10.87 26.25a8 8 0 0 0 1.49 7.06L40 125.84v4.32L25.11 148.8a8 8 0 0 0-1.48 7.06a107.6 107.6 0 0 0 10.88 26.25a8 8 0 0 0 6 3.93l23.72 2.64q1.49 1.56 3 3L70 215.46a8 8 0 0 0 3.94 6a107.7 107.7 0 0 0 26.25 10.87a8 8 0 0 0 7.06-1.49L125.84 216q2.16.06 4.32 0l18.64 14.92a8 8 0 0 0 7.06 1.48a107.2 107.2 0 0 0 26.25-10.88a8 8 0 0 0 3.93-6l2.64-23.72q1.56-1.48 3-3l23.78-2.8a8 8 0 0 0 6-3.94a107.7 107.7 0 0 0 10.87-26.25a8 8 0 0 0-1.49-7.06ZM128 168a40 40 0 1 1 40-40a40 40 0 0 1-40 40',
      },
    ],
  },
  close: {
    viewBox: '0 0 256 256',
    paths: [
      {
        fill: 'currentColor',
        d: 'M208.49 191.51a12 12 0 0 1-17 17L128 145l-63.51 63.49a12 12 0 0 1-17-17L111 128L47.51 64.49a12 12 0 0 1 17-17L128 111l63.51-63.52a12 12 0 0 1 17 17L145 128Z',
      },
    ],
  },
} satisfies Record<string, IconShape>;
